logo: # add logo name
title: Bef - Enjoy Freedom
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://everydavemylife.github.com" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video:  homepage-background.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: avatar.jpg # your photo
author-name: # your name
about-author: # about author
email: everydavemylife@gmail.com # your email
# phone: (496)-169-6557 # your pnone number
website: http://everydavemylife.github.com # you website

# Social link
# google_url:    # add url link
# twitter_url:   # add url link
instagram_url: instagram.com/everydavemylife # add url link
# instagram_url:  # add url link
# pinterest_url: # add url link
# dribbble_url:  # add url link
# facebook_url:  # add url link
youtube_url: https://www.youtube.com/channel/UCDsx5_A06S1sz8m6It86qdg

# Disqus
discus_identifier: mr-brown # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
